name: Deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm run deploy 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
